# Generated by Django 4.0.2 on 2022-02-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('serviceType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('docType', models.CharField(max_length=50)),
                ('docNumber', models.CharField(max_length=50)),
                ('role', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('state', models.IntegerField()),
                ('arrivalDate', models.DateField()),
                ('arrivalTime', models.TimeField()),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.service')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankTeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.service')),
            ],
        ),
    ]
