# Generated by Django 4.0.2 on 2022-02-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankteller',
            name='orderId',
        ),
        migrations.AddField(
            model_name='service',
            name='teller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.bankteller'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrivalDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrivalTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
