# Generated by Django 4.0.2 on 2022-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_bankteller_orderid_service_teller_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='docNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='docType',
            field=models.IntegerField(),
        ),
    ]
