# Generated by Django 4.0.2 on 2022-02-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_user_docnumber_alter_user_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='docNumber',
            field=models.BigIntegerField(),
        ),
    ]
