# Generated by Django 4.0.2 on 2022-03-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='serviceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.user'),
        ),
    ]
