# Generated by Django 4.0.2 on 2022-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_ticket_serviceid_alter_ticket_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='orderNumber',
            field=models.CharField(max_length=50),
        ),
    ]
