# Generated by Django 4.0.2 on 2022-03-16 03:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_remove_ticket_serviceid_ticket_serviceid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='updateTime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='LocationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.location'),
        ),
    ]
